# This file was generated by the {rix} R package v0.17.2 on 2025-10-28
# with following call:
# >rix(r_ver = "b798123f0980c8d8191f40a1ee86b7cff3132f2d",
#  > r_pkgs = cran_pkgs,
#  > system_pkgs = "html-tidy",
#  > tex_pkgs = c("amsmath",
#  > "inconsolata"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision b798123f0980c8d8191f40a1ee86b7cff3132f2d for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/b798123f0980c8d8191f40a1ee86b7cff3132f2d.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      devtools
      knitr
      progressr
      rcmdcheck
      rmarkdown
      testthat;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      inconsolata;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      html-tidy
      nix
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
