# This file was generated by the {rix} R package v0.17.2 on 2025-10-28
# with following call:
# >rix(r_ver = "f563fb5254c62e2486e6ead16d0e4af026496799",
#  > r_pkgs = cran_pkgs,
#  > system_pkgs = c("cmake",
#  > "mbedtls"),
#  > git_pkgs = git_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses upstream nixpkgs' revision f563fb5254c62e2486e6ead16d0e4af026496799 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/f563fb5254c62e2486e6ead16d0e4af026496799.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      knitr
      progressr
      rcmdcheck
      rmarkdown
      testthat;
  };
 
    mirai = (pkgs.rPackages.buildRPackage {
      name = "mirai";
      src = pkgs.fetchgit {
        url = "https://github.com/r-lib/mirai/";
        rev = "6895fea0853515f01deb67d3fd3890fcaf1105b0";
        sha256 = "sha256-OCp7G/HG/HCw4qRnyZ2/AXsOCNKyrI9BY8GB3ZOrtxU=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          nanonext;
      };
    });

    nanonext = (pkgs.rPackages.buildRPackage {
      name = "nanonext";
      src = pkgs.fetchgit {
        url = "https://github.com/r-lib/nanonext";
        rev = "ad23cd52ffcf7f6d285a525181a06aedf361541e";
        sha256 = "sha256-7f0I0XILh4IFImU3Vctd2ILnysc8lvDD1el5HWDA8zE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      cmake
      glibcLocales
      mbedtls
      nix
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ mirai nanonext rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
