# This file was generated by the {rix} R package v0.17.2 on 2025-10-30
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = cran_pkgs,
#  > system_pkgs = c("html-tidy",
#  > "qpdf"),
#  > tex_pkgs = c("amsmath",
#  > "inconsolata"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      knitr
      mirai
      progressr
      rcmdcheck
      rmarkdown
      testthat;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      inconsolata;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      html-tidy
      nix
      qpdf
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
