#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
  { id = "air-format",
    name = "air format",
    description = "Format R files with air.",
    entry = "air format",
    language = "system",
    files = "\\.(?i:R|Rmd|qmd)$",
    exclude = "renv/",
    pass_filenames = true,
  },
  { id = "jarl-check",
    name = "jarl check",
    description = "Check R files with jarl.",
    entry = "jarl check",
    language = "system",
    files = "\\.(?i:R|Rmd|qmd)$",
    exclude = "renv/",
    pass_filenames = true,
  },
  { id = "biome-format",
    name = "biome format",
    description = "Format JSON (and friends) with Biome.",
    entry = "biome format --write",
    language = "system",
    types_or = ["json"],
    exclude = "renv/",
    pass_filenames = true,
  },
  { id = "rumdl",
    name = "rumdl",
    description = "Lint Markdown files with rumdl.",
    entry = "rumdl check",
    language = "system",
    types = ["markdown"],
    pass_filenames = true,
  },
]

