---
title: "Reading Bruker OPUS binary files in R"
author: "Philipp Baumann"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Reading Bruker OPUS binary files in R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Bruker instruments produce a proprietary file format when measuring spectra. This way the Bruker OPUS software stores all measurement
parameters, configurations, environmental conditions, for different spectral data types as OPUS binary files.

Our package can read thosee binary files for most of the
Fourier-Transform(FT)-Infrared(IR)-spectrometers from Bruker Optics GmBH.

# Reading OPUS files

One can read both single OPUS files or a batch of many OPUS files. The main way to read files is

```r
library("opusreader2")
# example file
file <- opus_file()
data_list <- read_opus(dsn = file)
```

Thereby, `dsn` is the data source name, that currently either be a character vector of the folder path to read files from, or characters of OPUS file paths.


`read_opus()` parses into an R list (S3) of class "list_opusreader2". The data is arranged
as shown in the Bruker OPUS viewer:

```r
class(data_list)
# show data and metadata types
names(data_list)
```
For single OPUS files, there is also a lower level implementation.

```r
data_single <- read_opus_single(dsn = file)
```