get_nice_parameter_name <- function(parameter_name) {
  nice_name <- switch(EXPR = parameter_name,
    ACC = "Accessory",
    BMS = "Beamsplitter Setting",
    CHN = "Measurement Channel",
    CRM = "Correlation rejection mask",
    DTC = "Detector Setting",
    HPF = "High Pass Filter",
    OPF = "Optical Filter Setting",
    PGN = "Preamplifier Gain",
    RDX = "Extended Ready Check",
    SRC = "Source Setting",
    VEL = "Scanner Velocity",
    SON = "External Synchronisation",
    APF = "Apodization Function",
    HFQ = "End Frequency Limit for File",
    LFQ = "Start Frequency Limit for File",
    NLI = "Non Linearity Correction",
    PHR = "Phase Resolution",
    PHZ = "Phase Correction Mode",
    SPZ = "Stored Phase Mode",
    ZFF = "Zero Filling Factor",
    ADT = "Additional Data Treatment",
    AQM = "Acquisition Mode",
    COR = "Correlation Test Mode",
    DEL = "Delay Before Measurement",
    DLY = "Stabilization Delay",
    HFW = "Wanted High Frequency Limit",
    LFW = "Wanted Low Frequency Limit",
    NSS = "Sample Scans",
    PLF = "Result Spectrum",
    RES = "Resolution",
    SOT = "Sample Scans or Time",
    TCL = "Command line for Additional Data Treatment",
    TDL = "To do list",
    BLD = "Building",
    CNM = "Operation Name",
    CPY = "Company",
    DPM = "Department",
    EXP = "Experiment",
    LCT = "Location",
    SFM = "Sample Form",
    SNM = "Sample Name",
    XPP = "Experiment Path",
    IST = "Instrument Status",
    HFL = "Hight Folding Limit",
    LFL = "Low Folding Limit",
    LWN = "Laser Wavenumber",
    ABP = "Absolute Peak Pos in Laser*2",
    SSP = "Sample Spacing Divisor",
    HUM = "Relative Humidity Interferometer",
    RSN = "Running Sample Number",
    SRT = "Start time (sec)",
    DUR = "Scan time (sec)",
    TSC = "Scanner Temperature",
    MVD = "Max. Velocity Deviation",
    APG = "Actual preamplifier gain",
    HUA = "Absolute Humidity Interferometer",
    VSN = "Firmware version",
    SRN = "Instrument Serial Number",
    PKA = "Peak Amplitude",
    PKL = "Peak Location",
    GFW = "Number of Good FW Scans",
    BFW = "Number of Bad FW Scans",
    CRR = "Correlation rejection reason",
    PRA = "Backward Peack Amplitude",
    PRL = "Backward Peak Location",
    GBW = "Number of Good BW Scans",
    BBW = "Number of Bad BW Scans",
    INS = "Instrument Type",
    FOC = "Focal Length",
    RDY = "Ready Check",
    ARS = "Number of Background Scans",
    PGR = "Preamplifier Gain Background",
    RCH = "Extended Ready Check",
    NSR = "Background Scans",
    STR = "BG Scans or Time",
    DPF = "Data Point Format",
    NPT = "Number of Data Points",
    FXV = "Frequency of First Point",
    LXV = "Frequency of Last Point",
    CSF = "Y - Scaling Factor",
    MXY = "Y - Maximum",
    MNY = "Y - Minimum",
    DAT = "Date of Measurement",
    TIM = "Time of Measurement",
    DXU = "X Units",
    ASS = "Number of Sample Scans"
  )

  return(nice_name)
}

sort_list_by <- function(dataset_list) {
  sort_by <- c(
    "refl_data_param",
    "refl",
    "quant_report_refl",
    "spec_no_atm_comp_data_param",
    "spec_no_atm_comp",
    "spec_data_param",
    "spec",
    "sc_sample_data_param",
    "sc_sample",
    "sc_ref_data_param",
    "sc_ref",
    "optics",
    "optics_ref",
    "acquisition_ref",
    "fourier_transformation_ref",
    "fourier_transformation",
    "sample",
    "acquisition",
    "instrument_ref",
    "instrument",
    "lab_and_process_param",
    "lab_and_process_param_1",
    "lab_and_process_param_2",
    "info_block",
    "history"
  )

  to_sort_by <- intersect(sort_by, names(dataset_list))

  dataset_list <- dataset_list[to_sort_by]

  return(dataset_list)
}
